### PR TITLE
Task messaging

### PR DESCRIPTION
**Pull request by mkelley**
New `task.message` sub module to support task-to-user messages, which should be published to /stream.

* START_JOBS renamed to JOBS.
* FINISH_JOBS renamed to TASK_MESSAGES.
* With these updates, catch v0.3.6 can log messages to the task messaging stream.

### CODE REVIEW

**Comment by mkelley** [comment]
Example CLI output:
```
$ python3 scripts/catch-apis.py --base=http://localhost:5003/catch-local query/moving 63P
{'match': '63P', 'name': '63P', 'type': 'comet', 'valid': True}
{'job_id': '0eb65931fcf942a5816e6b76ecdad0ff', 'message': 'Enqueued search.  Listen to task messaging stream until job completed, then retrieve data from results URL.', 'query': "{'target': '63P', 'source': 'any', 'cached': True}", 'queued': True, 'results': 'http://localhost:5003/catch-local/caught/0eb65931fcf942a5816e6b76ecdad0ff'}
Connected to stream...
Starting moving target query.
Caught 0 observations in NEAT Palomar.
Caught 0 observations in NEAT GEODSS.
Task complete.
Nothing found.
```

**Comment by mkelley** [comment]
Stream output for the same query:
```
data: {"job_prefix": "0eb65931", "text": "Job queue number 1", "status": "queued"}

data: {"job_prefix": "0eb65931", "text": "Starting moving target query.", "status": "running"}

data: {"job_prefix": "0eb65931", "text": "Caught 0 observations in NEAT Palomar.", "status": "running"}

data: {"job_prefix": "0eb65931", "text": "Caught 0 observations in NEAT GEODSS.", "status": "running"}

data: {"job_prefix": "0eb65931", "text": "Task complete.", "status": "success"}
```

**Comment by dwd-umd** [comment]
Did this ever get merged?

**Comment by mkelley** [comment]
If we merge it, it will break the GUI.  I am proposing to use the "job_prefix" attribute to message user clients, rather than the full UUID.  This way we can preserve some user privacy.

**Comment by dwd-umd** [comment]
Please resolve conflicts then merge it. That will cause the stage deployment to get updated. I'll then adjust the frontend to work with this flow and when it's ready we can upgrade apis to production.

**Comment by mkelley** [comment]
:+1:

**Pull request merged**
